created geolocation component. I'm to display user latitude and longi…
cassandradanger/htg_restaurant_app pull request #2
Opened 2020-04-13 15:00 UTC by NextGenRecruiter

Set it up geolocation component.

2020-04-13 22:49 UTC, cassandradanger requested changes
Cool! Looks like some merge conflicts need to be addressed in App/App.js, but then I can approve :)

2020-04-14 01:58 UTC, NextGenRecruiter commented
resolved conflict.

2020-04-14 02:02 UTC, AbstractExplorer reviewed
Made changes to resolve conflict.

2020-04-14 02:31 UTC, uojiaku-ojiaku approved these changes

2020-04-14 14:08 UTC, cassandradanger approved these changes

2020-04-14 19:08 UTC, merged